# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  Default

jobs:
- deployment: VMDeploy
  displayName: Web deploy
  environment:
    name: prod_bot_env
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo here is where I deploy to the VM
        